  language: python

  cache: pip

  python:
    - "2.7"

  #skip installation process
  install: true

  git:
    depth: 50

  stages:
      - calidad del codigo

  flake8:
      stage: calidad del codigo
      tags:
        - python
      script:
        - ./test/getaddons.py

